async:
  executor:
    thread:
      core_pool_size: 30
      # 配置最大线程数
      max_pool_size: 30
      # 配置队列大小
      queue_capacity: 99988
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-importDB-